### ISSUE TITLE
error in xml files

### ISSUE THREAD

**Issue by anmar256** [shafihuzaib/hfeeds#2]
hi
i install your project
and made some xml files like http://vpnshop.in/xml/h574cc49982371.xml but it didn't work and a have error 500 can you tell me what is the problem?

**Comment by shafihuzaib** [comment]
Please submit the contents of this file.. **h574cc49982371.xml**

and also php_error_log (if possible)

**Comment by vanthang81** [comment]
hello, I also have the same problem, could you please help? I enclose the xml file. Thank you!
[h579a0b91ea411.xml.zip](https://github.com/shafihuzaib/hfeeds/files/390300/h579a0b91ea411.xml.zip)

**Comment by shafihuzaib** [comment]
@vanthang81 Please let me know the server details you've installed this script on.. Operating System, Apache / NGinx Server etc

**Comment by vanthang81** [comment]
please share your email, I'll send you link to phpinfo. My email: @gmail.com

**Comment by shafihuzaib** [comment]
Please share your email address.
Furthermore, please replace the contents of **.htaccess** file in **xml** directory by either of the following instructions:

`AddHandler application/x-httpd-php .xml`
OR
`AddHandler x-httpd-php .xml`
OR
`AddHandler application/x-httpd-php5 .xml`
OR
`AddHandler x-httpd-php5 .xml`

**Comment by vanthang81** [comment]
My email: vanthang81@gmail

**Comment by vanthang81** [comment]
I already tried those alternative contents in .htaccess file in xml directory but without luck :(

**Comment by vanthang81** [comment]
Attached is the error when I open from browser
![2016-07-29 at 9 54 pm](https://cloud.githubusercontent.com/assets/20704919/17252471/0f6f2f2e-55d7-11e6-8d00-4f482b43e8fa.png)

**Comment by shafihuzaib** [comment]
check the source code..in the browser.. is it php code? If yes, then your xml files are not being parsed by PHP handler.. please checkout [this article](http://www.shafihuzaib.com/developer-admin/parse-html-as-php-htaccess-way-different-ways) for various possible htaccess configurations..

**Comment by vanthang81** [comment]
:( I tried all of them, not work at all. Please send me an email, I'll send you the link.

**Comment by shafihuzaib** [comment]
Email sent.. Please check & respond

**Comment by shafihuzaib** [comment]
For anyone else facing this error, please re-check & re-download. I've updated the whole code of the repository (master branch)

**Comment by YogSottot** [comment]
For those using nginx with php-fpm.  
That is, there is no support for .htaccess  

Add to php-fpm config
```security.limit_extensions = .php .phar .xml```

Example of nginx location
```
location ~* /hfeeds/xml/ {
            fastcgi_pass unix:/run/php-fpm/rss.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
  }
```
